rpc:
  listen: unix:///tmp/rr.sock

server:
  command: "php ../roadrunner/tests/psr-worker-bench.php"
  relay: "pipes"
  relay_timeout: "20s"

http:
  address: 127.0.0.1:15395
  max_request_size: 1024
  middleware: [ ]
  trusted_subnets: [ "10.0.0.0/8", "127.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16", "::1/128", "fc00::/7", "fe80::/10" ]
  pool:
    num_workers: 10
    max_jobs: 0
    allocate_timeout: 60s
    destroy_timeout: 60s

logs:
  mode: production
  level: error
