rpc:
  listen: unix:///tmp/rr.sock

server:
  command: "php ../roadrunner/tests/temporal-worker.php"
  relay: "pipes"
  relay_timeout: "20s"

temporal:
  address: 127.0.0.1:7233
  activities:
    debug: false
    num_workers: 5
    max_jobs: 64
    allocate_timeout: 60s
    destroy_timeout: 60s
  codec: proto
  debug_level: 2

logs:
  mode: production
  level: debug

